#!/usr/bin/env bash

check_factor() {
    num=$1
    factors=$(factor "$num")
    factors=${factors#"$num: "}
    IFS=' ' read -ra primes <<< "$factors"

    if [ "${#primes[@]}" -eq 2 ]; then
        echo "$num=${primes[0]}*${primes[1]}"
    else
        echo "Unable to factorize $num"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

while IFS= read -r num; do
    check_factor "$num" || echo "Unable to factorize $num"
done < "$1"
